FROM continuumio/miniconda3:latest

COPY environment.yml .

RUN conda install -n base -c conda-forge mamba -y && \
    mamba env update -n base -f environment.yml && \
    conda clean --all --yes

ENV PATH="/opt/conda/bin:${PATH}"