FROM continuumio/miniconda3:latest

RUN conda update -n base conda -y && \
    conda install -n base conda-libmamba-solver -y && \
    conda config --set solver libmamba

COPY environment.yml .

RUN conda env update -n base -f environment.yml --solver libmamba && \
    conda clean --all --yes

ENV PATH="/opt/conda/bin:${PATH}"